# В конце 12-finalize.sh ЗАМЕНИ финальное сообщение на:

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✅ INSTALLATION COMPLETE (PANEL NOT STARTED)             ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT: Panel NOT started automatically${NC}"
echo -e "   To prevent SSH lockout on low-memory systems:"
echo ""
echo -e "${CYAN}🚀 SAFE START (recommended):${NC}"
echo -e "   panel-safe-start"
echo ""
echo -e "${BLUE}🔑 Credentials:${NC}"
echo -e "   cat ${CRED_FILE}"
echo ""
echo -e "${GREEN}🌐 Access after start:${NC}"
echo -e "   http://$(hostname -I | awk '{print $1}'):3000"
echo ""
echo -e "${RED}❌ NEVER run this directly (causes SSH lockout):${NC}"
echo -e "   sudo -u panel pm2 start /opt/panel/backend/ecosystem.config.js"
echo ""